#Project info
site_name: Songpress - Il Canzonatore
site_description: "Songpress is a free, easy to use song typeset program for Linux and Windows, that generates high-quality songbooks."
site_url: https://songpress.skeed.it

#Repository
repo_name: "lallulli/songpress"
repo_url: "https://github.com/lallulli/songpress"
edit_uri: ""

#Copyright
copyright: 'Copyright (c) 2026 <a href="https://skeed.it/luca">Luca Allulli</a>.<br>Songpress is licensed under the <a href="https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html">GNU General Public License version 2</a>'

#Configuration
site_dir: _site
theme:
  name: material
  palette:
    primary: deep orange
  features:
    - navigation.tabs
    - navigation.top
    - navigation.footer
  logo: assets/songpress_icon.png
  favicon: assets/favicon.ico

#Navigation menu
nav:
  - Home: index.md
  - Documentation:
      - Getting Started: manual/getting_started.md
      - ChordPro: manual/chordpro.md
      - Example: manual/example.md
      - Exporting: manual/exporting.md
      - Transposing: manual/transposing.md
      - Chord Simplification: manual/chord_simplification.md
      - Quick Editing Cords: manual/quick_editing.md
      - Format conversion: manual/format_conversion.md
  - News:
    - 2026:
      - news/songpress-1.9.md
      - news/songpress-1.9.0rc1.md
    - 2021:
      - news/songpress-1.8.md
    - 2019:
      - news/songpress-1.7.md
    - 2015:
      - news/songpress-1.6.md
    - 2013:
      - news/songpress-1.5.md
    - 2012:
      - news/songpress-1.4.2.md
    - 2011:
      - news/songpress-1.4.1.md
      - news/songpress-1.4.md
      - news/sub-to-mercurial.md
    - 2010:
      - news/songpress-1.3.md
      - news/songpress-1.2.md
    - 2009:
      - news/songpress-1.1.md
      - news/autodetecting-song-key.md


  - Screenshots: screenshots.md
  - About:
      - History: history.md
      - Contribute: contribute.md
      - License: license.md

  - Skeed: https://www.skeed.it

#Useful markdown extensions
markdown_extensions:
  - admonition
  - attr_list
  - tables
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

#Plugins
plugins:
  - search
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: en
          default: true
          name: English
          build: true
          site_name: "Songpress - Il Canzonatore (en)"
        - locale: it
          name: Italiano
          build: true
          site_name: "Songpress - Il Canzonatore (it)"
          nav_translations:
            Documentation: Documentazione
            Getting Started: Per Iniziare
            ChordPro: Formato ChordPro
            Example: Esempio
            Exporting: Esportazione
            Transposing: Trasposizione e notazione
            Chord Simplification: Semplificazione accordi
            Quick Editing Cords: Modifica rapida accordi
            Format conversion: Conversione formati
            About: Informazioni
            History: Storia
            Contribute: Contribuire
            License: Licenza
